[agent]
name = "orchestrator-agent"
version = "1.0.0"
description = "PR Summarizer Orchestrator Agent - Coordinates user interaction and workflow management"

[options.ORCHESTRATOR_API_KEY]
type = "string"
description = "NEBIUS API Key for orchestrator agent"

[options.GITHUB_TOKEN]
type = "string"
description = "GitHub Personal Access Token for PR fetching"

[options.CORAL_CONNECTION_URL]
type = "string"
description = "Coral Server connection URL (provided by Coral Server)"
default = ""

[options.CORAL_PROMPT_SYSTEM]
type = "string"
description = "Additional system prompt for Coral integration"
default = ""

[options.CORAL_AGENT_ID]
type = "string"
description = "Coral agent identifier"
default = "orchestrator-agent"

[runtimes.executable]
command = ["bash", "../agents/venv.sh", "agents/orchestrator_agent.py"]