[agent]
name = "risk-agent"
version = "1.0.0"
description = "PR Risk Assessment Agent - Analyzes security and quality risks in GitHub pull requests"

[options]
RISK_API_KEY = { type = "string", description = "AIML API Key for risk assessment agent" }
GITHUB_TOKEN = { type = "string", description = "GitHub Personal Access Token for PR fetching" }
CORAL_CONNECTION_URL = { type = "string", description = "Coral Server connection URL (provided by Coral Server)", default = "" }
CORAL_PROMPT_SYSTEM = { type = "string", description = "Additional system prompt for Coral integration", default = "" }

[runtimes.executable]
command = ["bash", "../agents/venv.sh", "agents/risk_agent.py"]